use starschema;

CREATE TABLE DimSalesReason(
	[SalesReasonKey] [int] IDENTITY(1,1) NOT NULL,
	[SalesReasonID] [int] NOT NULL,
	[Name] nvarchar(50) NOT NULL,
	[ReasonType] nvarchar(50) NOT NULL,
	CONSTRAINT [PK_SalesReason_SalesReasonKey] PRIMARY KEY ([SalesReasonKey])
);
CREATE TABLE DimSpecialOffer(
	[SpecialOfferKey] [int] IDENTITY(1,1) NOT NULL,
	[SpecialOfferID] [int] NOT NULL,
	[Description] [nvarchar](255) NOT NULL,
	[DiscountPct] [smallmoney] NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[Category] [nvarchar](50) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[MinQty] [int] NOT NULL,
	[MaxQty] [int] NULL,
	CONSTRAINT [PK_SpecialOffer_SpecialOfferKey] PRIMARY KEY ([SpecialOfferKey])
);
CREATE TABLE DimCustomer(
	[CustomerKey] [int] IDENTITY(1,1) NOT NULL,
	[CustomerID] [int] NOT NULL,
	[PersonType] [nchar](2) NULL,
	[NameStyle] bit NULL,
	[Title] [nvarchar](8) NULL,
	[FirstName] nvarchar(50) NULL,
	[MiddleName] nvarchar(50) NULL,
	[LastName] nvarchar(50) NULL,
	[Suffix] [nvarchar](10) NULL,
	[EmailPromotion] [int] NULL,
	[StoreName] nvarchar(50) NULL,
	CONSTRAINT [PK_Customer_CustomerKey] PRIMARY KEY ([CustomerKey])
);
CREATE TABLE DimEmployee(
	[EmployeeKey] [int] IDENTITY(1,1) NOT NULL,
	[BusinessEntityID] [int] NOT NULL,
	[SalesQuota] [money] NULL,
	[Bonus] [money] NULL,
	[CommissionPct] [smallmoney] NULL,
	[SalesYTD] [money] NULL,
	[SalesLastYear] [money] NULL,
	[SalesPersonFlag] [bit] NOT NULL,	
	[JobTitle] [nvarchar](50) NOT NULL,
	[BirthDate] [date] NOT NULL,
	[MaritalStatus] [nchar](1) NOT NULL,
	[Gender] [nchar](1) NOT NULL,
	[HireDate] [date] NOT NULL,
	[SalariedFlag] bit NOT NULL,
	[VacationHours] [smallint] NOT NULL,
	[SickLeaveHours] [smallint] NOT NULL,
	[CurrentFlag] bit NOT NULL,
	[PersonType] [nchar](2) NOT NULL,
	[NameStyle] bit NOT NULL,
	[Title] [nvarchar](8) NULL,
	[FirstName] nvarchar(50) NOT NULL,
	[MiddleName] nvarchar(50) NULL,
	[LastName] nvarchar(50) NOT NULL,
	[Suffix] [nvarchar](10) NULL,
	[EmailPromotion] [int] NOT NULL,
	CONSTRAINT [PK_DimEmployee_EmployeeKey] PRIMARY KEY (EmployeeKey)
);
CREATE TABLE DimVendor(
	[VendorKey] [int] IDENTITY(1,1) NOT NULL,
	[BusinessEntityID] [int] NOT NULL,
	[Name] nvarchar(50) NOT NULL,
	[CreditRating] [tinyint] NOT NULL,
	[PreferredVendorStatus] bit NOT NULL,
	[ActiveFlag] bit NOT NULL,
 CONSTRAINT [PK_DimVendor_VendorKey] PRIMARY KEY ([VendorKey])
);
CREATE TABLE DimShipMethod(
	[ShipMethodKey] [int] IDENTITY(1,1) NOT NULL,
	[ShipMethodID] [int] NOT NULL,
	[Name] nvarchar(50) NOT NULL,
	[ShipBase] [money] NOT NULL,
	[ShipRate] [money] NOT NULL,
 CONSTRAINT [PK_DimShipMethod_ShipMethodKey] PRIMARY KEY ([ShipMethodKey])
);
CREATE TABLE DimSalesTerritory(
	[SalesTerritoryKey] [int] IDENTITY(1,1) NOT NULL,
	[TerritoryID] [int] NOT NULL,
	[SalesTerritoryName] nvarchar(50) NOT NULL,
	[Group] [nvarchar](50) NOT NULL,
	[SalesYTD] [money] NOT NULL,
	[SalesLastYear] [money] NOT NULL,
	[CostYTD] [money] NOT NULL,
	[CostLastYear] [money] NOT NULL,
	[CountryRegionName] nvarchar(50) NOT NULL,
	CONSTRAINT [PK_DimSalesTerritory_SalesTerritoryKey] PRIMARY KEY ([SalesTerritoryKey])
);
CREATE TABLE DimProduct(
	[ProductKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [int] NOT NULL,
	[ProductName] nvarchar(50) NOT NULL,
	[ProductNumber] [nvarchar](25) NOT NULL,
	[MakeFlag] bit NOT NULL,
	[FinishedGoodsFlag] bit NOT NULL,
	[Color] [nvarchar](15) NULL,
	[SafetyStockLevel] [smallint] NOT NULL,
	[ReorderPoint] [smallint] NOT NULL,
	[StandardCost] [money] NOT NULL,
	[ListPrice] [money] NOT NULL,
	[Size] [nvarchar](5) NULL,
	[Weight] [decimal](8, 2) NULL,
	[DaysToManufacture] [int] NOT NULL,
	[ProductLine] [nchar](2) NULL,
	[Class] [nchar](2) NULL,
	[Style] [nchar](2) NULL,
	[ProductSubcategoryName] nvarchar(50) NULL,
	[ProductCategoryName] nvarchar(50) NULL,
	[SellStartDate] [datetime] NOT NULL,
	[SellEndDate] [datetime] NULL,
	[DiscontinuedDate] [datetime] NULL,
	[ProductModelName] nvarchar(50) NULL,
	[SizeUnitMeasureName] nvarchar(50) NULL,
	[WeightUnitMeasureName] nvarchar(50) NULL,
	CONSTRAINT [PK_DimProduct_ProductKey] PRIMARY KEY ([ProductKey])
);
CREATE TABLE DimCurrency(
	[CurrencyKey] [int] IDENTITY(1,1) NOT NULL,
	[CurrencyRateID] [int] NOT NULL,
	[CurrencyRateDate] [datetime],
	[FromCurrencyName] nvarchar(50),
	[ToCurrencyName] nvarchar(50),
	[AverageRate] [money],
	[EndOfDayRate] [money],
 CONSTRAINT [PK_DimCurrency_CurrencyKey] PRIMARY KEY ([CurrencyKey])
); 
CREATE TABLE DimAddress(
	[AddressKey] [int] IDENTITY(1,1) NOT NULL,
	[AddressID] [int] NOT NULL,
	[AddressLine1] [nvarchar](60) NOT NULL,
	[AddressLine2] [nvarchar](60) NULL,
	[City] [nvarchar](30) NOT NULL,
	[PostalCode] [nvarchar](15) NOT NULL,
	[SpatialLocation] [geography] NULL,
	[StateProvinceCode] [nchar](3) NOT NULL,
	[IsOnlyStateProvinceFlag] bit NOT NULL,
	[StateProvinceName] nvarchar(50) NOT NULL,
	[CountryRegionName] nvarchar(50) NOT NULL,
	CONSTRAINT [PK_DimAddress_AddressKey] PRIMARY KEY ([AddressKey])
);
CREATE TABLE DimDate(
	[DateKey] [int] IDENTITY(1,1) NOT NULL,
	[Date] [Date] NOT NULL,
	[Month] [tinyint] NOT NULL,
	[Year] [int] NOT NULL,
	[DayOfWeek] [tinyint] NOT NULL,
	[Quarter] varchar(2) NOT NULL,
	CONSTRAINT [PK_DimDate_DateKey] PRIMARY KEY ([DateKey])
);
CREATE TABLE FactSalesReason(
	SalesReasonKey [int] NOT NULL,
	SalesOrderNumber  nvarchar(25),
	CONSTRAINT FK_FactSalesReason_DimSalesReason FOREIGN KEY (SalesReasonKey) REFERENCES DimSalesReason(SalesReasonKey),
	CONSTRAINT PK_FactSalesReason_SalesOrderNumber_SalesReasonKey PRIMARY KEY (SalesOrderNumber, SalesReasonKey)
);
CREATE TABLE FactOnlineSales(
	ProductKey [int] NOT NULL,
	CustomerKey [int] NOT NULL,
	CurrencyKey [int] NOT NULL,
	SpecialOfferKey [int] NOT NULL,
	OrderDateKey [int] NOT NULL,
	DueDateKey [int] NOT NULL,
	ShipDateKey [int] NOT NULL,
	ShipToAddressKey [int] NOT NULL,
	BillToAddressKey [int] NOT NULL,
	SalesTerritoryKey [int] NOT NULL,
	ShipMethodKey [int] NOT NULL,
	SalesOrderNumber  nvarchar(25),
	SalesOrderDetailID [int] NOT NULL,
	OrderQuantity [smallint] NOT NULL,
	RevisionNumber [tinyint] NOT NULL,
	Status [tinyint] NOT NULL,
	UnitCost [money] NOT NULL,
	UnitSellingPrice [money] NOT NULL,
	UnitSellingPriceDiscount [money] NOT NULL,
	LineTotalSellingPrice AS (isnull(([UnitSellingPrice]*((1.0)-[UnitSellingPriceDiscount]))*[OrderQuantity],(0.0))),
	LineTotalDiscount AS (isnull(([UnitSellingPrice]*([UnitSellingPriceDiscount]))*[OrderQuantity],(0.0))),	
	LineTotalGrossMarginPct AS (isnull(([UnitSellingPrice]-[UnitCost])/[UnitSellingPrice],(0.0))),		
	SubTotal [money] NOT NULL,
	TaxAmt [money] NOT NULL,
	Freight [money] NOT NULL,
	TotalPrice  AS (isnull(([SubTotal]+[TaxAmt])+[Freight],(0))),
	CONSTRAINT FK_FactOnlineSales_DimProduct FOREIGN KEY (ProductKey) REFERENCES DimProduct(ProductKey),
	CONSTRAINT FK_FactOnlineSales_DimCustomer FOREIGN KEY (CustomerKey) REFERENCES DimCustomer(CustomerKey),
	CONSTRAINT FK_FactOnlineSales_DimCurrency FOREIGN KEY (CurrencyKey) REFERENCES DimCurrency(CurrencyKey),
	CONSTRAINT FK_FactOnlineSales_DimSpecialOffer FOREIGN KEY (SpecialOfferKey) REFERENCES DimSpecialOffer(SpecialOfferKey),
	CONSTRAINT FK_FactOnlineSales_DimOrderDate FOREIGN KEY (OrderDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactOnlineSales_DueDate FOREIGN KEY (DueDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactOnlineSales_ShipDate FOREIGN KEY (ShipDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactOnlineSales_ShipToAddress FOREIGN KEY (ShipToAddressKey) REFERENCES DimAddress(AddressKey),
	CONSTRAINT FK_FactOnlineSales_BillToAddress FOREIGN KEY (BillToAddressKey) REFERENCES DimAddress(AddressKey),
	CONSTRAINT FK_FactOnlineSales_DimSalesTerritory FOREIGN KEY (SalesTerritoryKey) REFERENCES DimSalesTerritory(SalesTerritoryKey),
	CONSTRAINT FK_FactOnlineSales_DimShipMethod FOREIGN KEY (ShipMethodKey) REFERENCES DimShipMethod(ShipMethodKey),
	CONSTRAINT PK_FactOnlineSales_SalesOrderNumber_SalesOrderDetailID PRIMARY KEY (SalesOrderNumber, SalesOrderDetailID)
);
CREATE TABLE FactRetailSales(
	ProductKey [int] NOT NULL,
	CustomerKey [int] NOT NULL,
	EmployeeKey [int],
	CurrencyKey [int] NOT NULL,
	SpecialOfferKey [int] NOT NULL,
	OrderDateKey [int] NOT NULL,
	DueDateKey [int] NOT NULL,
	ShipDateKey [int] NOT NULL,
	ShipToAddressKey [int] NOT NULL,
	BillToAddressKey [int] NOT NULL,
	SalesTerritoryKey [int] NOT NULL,
	ShipMethodKey [int] NOT NULL,
	SalesOrderNumber  nvarchar(25),
	SalesOrderDetailID [int] NOT NULL,
	OrderQuantity [smallint] NOT NULL,
	RevisionNumber [tinyint] NOT NULL,
	Status [tinyint] NOT NULL,
	UnitCost [money] NOT NULL,
	UnitSellingPrice [money] NOT NULL,
	UnitSellingPriceDiscount [money] NOT NULL,
	LineTotalSellingPrice AS (isnull(([UnitSellingPrice]*((1.0)-[UnitSellingPriceDiscount]))*[OrderQuantity],(0.0))),
	LineTotalDiscount AS (isnull(([UnitSellingPrice]*([UnitSellingPriceDiscount]))*[OrderQuantity],(0.0))),	
	LineTotalGrossMarginPct AS (isnull(([UnitSellingPrice]-[UnitCost])/[UnitSellingPrice],(0.0))),
	SubTotal [money] NOT NULL,
	TaxAmt [money] NOT NULL,
	Freight [money] NOT NULL,
	TotalPrice  AS (isnull(([SubTotal]+[TaxAmt])+[Freight],(0))),
	CONSTRAINT FK_FactRetailSales_DimProduct FOREIGN KEY (ProductKey) REFERENCES DimProduct(ProductKey),
	CONSTRAINT FK_FactRetailSales_DimCustomer FOREIGN KEY (CustomerKey) REFERENCES DimCustomer(CustomerKey),
	CONSTRAINT FK_FactRetailSales_DimEmployee FOREIGN KEY (EmployeeKey) REFERENCES DimEmployee(EmployeeKey),
	CONSTRAINT FK_FactRetailSales_DimCurrency FOREIGN KEY (CurrencyKey) REFERENCES DimCurrency(CurrencyKey),
	CONSTRAINT FK_FactRetailSales_DimSpecialOffer FOREIGN KEY (SpecialOfferKey) REFERENCES DimSpecialOffer(SpecialOfferKey),
	CONSTRAINT FK_FactRetailSales_OrderDate FOREIGN KEY (OrderDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactRetailSales_DueDate FOREIGN KEY (DueDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactRetailSales_ShipDate FOREIGN KEY (ShipDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactRetailSales_ShipToAddress FOREIGN KEY (ShipToAddressKey) REFERENCES DimAddress(AddressKey),
	CONSTRAINT FK_FactRetailSales_BillToAddress FOREIGN KEY (BillToAddressKey) REFERENCES DimAddress(AddressKey),
	CONSTRAINT FK_FactRetailSales_DimSalesTerritory FOREIGN KEY (SalesTerritoryKey) REFERENCES DimSalesTerritory (SalesTerritoryKey),
	CONSTRAINT FK_FactRetailSales_DimShipMethod FOREIGN KEY (ShipMethodKey) REFERENCES DimShipMethod(ShipMethodKey),
	CONSTRAINT PK_FactRetailSales_SalesOrderNumber_SalesOrderDetailID PRIMARY KEY (SalesOrderNumber, SalesOrderDetailID)
);
CREATE TABLE FactPurchaseOrder(
	ProductKey [int] NOT NULL,
	EmployeeKey [int] NOT NULL,
	ShipMethodKey [int] NOT NULL,
	VendorKey [int] NOT NULL,	
	DueDateKey [int] NOT NULL,
	ShipDateKey [int] NOT NULL,
	OrderDateKey [int] NOT NULL,	
	PurchaseOrderID [int] NOT NULL,
	PurchaseOrderDetailID [int] NOT NULL,
	RevisionNumber [tinyint] NOT NULL,
	Status [tinyint] NOT NULL,
	OrderQty [smallint] NOT NULL,
	UnitCost [money] NOT NULL,
	LineTotal AS (isnull([OrderQty]*[UnitCost],(0.00))),
	ReceivedQty [decimal](8, 2) NOT NULL,
	RejectedQty [decimal](8, 2) NOT NULL,
	StockedQty  AS (isnull([ReceivedQty]-[RejectedQty],(0.00))),
	SubTotal [money] NOT NULL,
	TaxAmt [money] NOT NULL,
	Freight [money] NOT NULL,
	TotalPrice  AS (isnull(([SubTotal]+[TaxAmt])+[Freight],(0))) PERSISTED NOT NULL,
	CONSTRAINT FK_FactPurchaseOrder_DimProduct FOREIGN KEY (ProductKey) REFERENCES DimProduct(ProductKey),
	CONSTRAINT FK_FactPurchaseOrder_DimEmployee FOREIGN KEY (EmployeeKey) REFERENCES DimEmployee(EmployeeKey),
	CONSTRAINT FK_FactPurchaseOrder_DimShipMethod FOREIGN KEY (ShipMethodKey) REFERENCES DimShipMethod(ShipMethodKey),
	CONSTRAINT FK_FactPurchaseOrder_DimVendor FOREIGN KEY (VendorKey) REFERENCES DimVendor(VendorKey),
	CONSTRAINT FK_FactPurchaseOrder_DueDate FOREIGN KEY (DueDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactPurchaseOrder_ShipDate FOREIGN KEY (ShipDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT FK_FactPurchaseOrder_OrderDate FOREIGN KEY (OrderDateKey) REFERENCES DimDate(DateKey),
	CONSTRAINT PK_FactPurchaseOrder_PurchaseOrderID_PurchaseOrderDetailID PRIMARY KEY (PurchaseOrderID, PurchaseOrderDetailID)
);
